### PR TITLE
Updating some Gem Versions

### PR DESCRIPTION
**Pull request by cosmoburn**
Using Ruby 2.2.0 Required these version updates.

### CODE REVIEW

**Comment by chaserx** [comment]
Are these versions also backwards compatible with ruby 1.9.3? Which is what I think the server is running?

**Comment by mikedillion** [comment]
Maybe!

**Comment by chaserx** [comment]
+1

**Comment by ArthurSilveira** [comment]
haha, I switched versions on my laptop and it seems to work. Not sure I did it right though, if someone else wants to double check.

**Comment by chaserx** [comment]
We could probably stand to target Ruby 2.2 anyway. Live in the future.

**Pull request merged**
